language: node_js
node_js:
  - "4.1"
install:
  - npm install
script:
  - grunt build-dist
  - grunt gh-pages
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: 'build'
    github_token: $GITHUB_TOKEN
    on:
      branch: master
