language: node_js
node_js:
  - "10"
install:
  - yarn install
script:
  - grunt build-dist
  - grunt gh-pages
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: 'build'
    github_token: $GITHUB_TOKEN
    on:
      branch: master
notifications:
  slack: performix:yXTihlSzsLFSZiqbXMNzvTSX

