language: node_js
node_js:
  - 10
cache: false
install:
  - yarn install
script:
  - yarn build
  - yarn test
  - yarn browserstack
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: 'dist'
    github_token: $GITHUB_TOKEN
    on:
      branch: master
notifications:
  slack: performix:yXTihlSzsLFSZiqbXMNzvTSX

