---
version: 2
plan:
  project-key: AJL
  key: EXTCSSTEST
  name: extended-css - test new

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x
            # Fix mixed logs
            exec 2>&1

            docker build \
              --file Dockerfile \
              --progress plain \
              --secret id=BROWSERSTACK_USER,env=bamboo_browserstackUser \
              --secret id=BROWSERSTACK_KEY,env=bamboo_browserstackPassword \
              --target test-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh output/artifacts/extended-css.js"
  artifacts:
    - name: extended-css.js
      location: output/artifacts
      pattern: extended-css.js
      required: true
  requirements:
    - extension: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

labels: []
other:
  concurrent-build-plugin: system-default
