name: Deploy ExtendedCSS to GitHub Pages

on:
  push:
    tags:
      - v*

env:
  PNPM_VERSION: 10.33.4

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: pnpm build
        run: pnpm build

      - name: pnpm test local
        run: pnpm test local

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          branch: gh-pages
          clean: true

  notify:
    needs:
      - deploy
    if:
      ${{ always() &&
        (
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@v3

      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: workflow, repo, message, commit, author, eventName, ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
